export type Question = {
  prompt: string;
  options: string[];
  answer: number;
};

export type Lesson = {
  id: string;
  term: string;
  week: number;
  title: string;
  shortTitle: string;
  focus: string;
  outcome: string;
  vocab: string[];
  starter: string;
  model: string;
  guided: string;
  challenge: string;
  exitTicket: string;
  scratchHint: string;
  teacherNote: string;
  scratchEditorUrl: string;
  scratchStarterUrl: string;
  scratchEmbedUrl: string;
  questions: Question[];
};

const editorUrl = "https://scratch.mit.edu/projects/editor/?tutorial=getStarted";
const studioUrl = "https://scratch.mit.edu/studios/";
const embedUrl = "https://scratch.mit.edu/projects/embed/10128407/";

export const lessons: Lesson[] = [
  {
    id: "st1w1",
    term: "Summer Term 1",
    week: 1,
    title: "Conditions",
    shortTitle: "Intro to Conditions",
    focus: "Understanding conditions in Scratch",
    outcome: "I can explain that a condition can be true or false.",
    vocab: ["condition", "true", "false", "decision"],
    starter: "Think about real life decisions: If it rains, what happens next?",
    model: "Look at Scratch condition blocks and test when something is true or false.",
    guided: "Try simple true/false checks with a partner.",
    challenge: "Change the condition so the action happens in a different situation.",
    exitTicket: "A condition in code can only be true or false.",
    scratchHint: "Create a sprite action that only happens when one rule is true.",
    teacherNote: "Keep the language concrete. Use physical examples before moving into Scratch.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "A condition is...", options: ["A picture", "A decision check", "A type of sprite"], answer: 1 },
      { prompt: "True or false: A condition helps code decide what to do.", options: ["True", "False"], answer: 0 },
    ],
  },
  {
    id: "st1w2",
    term: "Summer Term 1",
    week: 2,
    title: "If... Then...",
    shortTitle: "Single Outcome Selection",
    focus: "Using if... then... in Scratch",
    outcome: "I can use an if... then... block to make a simple decision.",
    vocab: ["if", "then", "selection", "action"],
    starter: "What should happen if the sprite touches the edge?",
    model: "Build a short script where one condition triggers one action.",
    guided: "Copy a basic if... then... program and test it.",
    challenge: "Swap the condition or action and predict the result.",
    exitTicket: "An if... then... block only runs the code when the condition is true.",
    scratchHint: "Try making a sprite speak only when it touches a colour or edge.",
    teacherNote: "Model the difference between code that always runs and code that only runs when a condition is met.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "What happens if the condition is false in an if... then... block?", options: ["The action runs", "Nothing inside the block runs", "Scratch crashes"], answer: 1 },
      { prompt: "Which word means making a decision in code?", options: ["Loop", "Selection", "Variable"], answer: 1 },
    ],
  },
  {
    id: "st1w3",
    term: "Summer Term 1",
    week: 3,
    title: "If... Then... Else...",
    shortTitle: "Branching",
    focus: "Using two outcomes in Scratch",
    outcome: "I can create code with two different outcomes.",
    vocab: ["branch", "outcome", "else", "selection"],
    starter: "If the answer is right, what should happen? If it is wrong, what should happen?",
    model: "Demonstrate one path for true and another path for false.",
    guided: "Build a simple quiz question with correct and incorrect responses.",
    challenge: "Improve the feedback so each outcome is clearer.",
    exitTicket: "If... then... else... lets a program choose between two outcomes.",
    scratchHint: "Use different sounds or messages for correct and incorrect answers.",
    teacherNote: "Keep returning to the phrase: one condition, two possible outcomes.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "Why is else useful?", options: ["It gives a second outcome", "It makes sprites bigger", "It repeats code"], answer: 0 },
      { prompt: "A program that gives one message for correct and another for incorrect is using...", options: ["branching", "drawing", "timers"], answer: 0 },
    ],
  },
  {
    id: "st1w4",
    term: "Summer Term 1",
    week: 4,
    title: "Selection + Loops",
    shortTitle: "Continuous Checking",
    focus: "Using selection inside repetition",
    outcome: "I can explain how a program keeps checking for an event.",
    vocab: ["loop", "repeat", "forever", "check"],
    starter: "How does a game keep noticing a key press?",
    model: "Show a forever loop that repeatedly checks a condition.",
    guided: "Create a script that responds while the program is running.",
    challenge: "Add a second response inside the loop.",
    exitTicket: "A loop can keep checking a condition again and again.",
    scratchHint: "Make a sprite keep checking for a key press, collision, or colour touch.",
    teacherNote: "Pupils often think one check is enough. Emphasise live checking during the whole program.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "Why put a condition inside a forever loop?", options: ["To keep checking it", "To delete the sprite", "To slow the computer"], answer: 0 },
      { prompt: "Which block is best for continuous checking?", options: ["Forever", "Say", "Go to x:y"], answer: 0 },
    ],
  },
  {
    id: "st1w5",
    term: "Summer Term 1",
    week: 5,
    title: "Asking Questions",
    shortTitle: "Input + Decisions",
    focus: "Using ask/answer with conditions",
    outcome: "I can use a player's answer inside a condition.",
    vocab: ["input", "answer", "question", "response"],
    starter: "How can a computer ask a user a question?",
    model: "Use ask and answer, then compare the answer in an if statement.",
    guided: "Make one interactive question in Scratch.",
    challenge: "Accept more than one correct answer or improve the feedback.",
    exitTicket: "The answer block stores what the user typed.",
    scratchHint: "Use a single question first, then compare the answer to the correct response.",
    teacherNote: "Model exact matching clearly and discuss what happens if the user types something unexpected.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "What does the answer block contain?", options: ["The last thing the user typed", "A random number", "The sprite name"], answer: 0 },
      { prompt: "The ask block is useful because it makes a program...", options: ["interactive", "invisible", "quieter"], answer: 0 },
    ],
  },
  {
    id: "st1w6",
    term: "Summer Term 1",
    week: 6,
    title: "Designing a Quiz",
    shortTitle: "Planning Logic",
    focus: "Planning a Scratch quiz before coding",
    outcome: "I can plan the steps and decisions for a quiz program.",
    vocab: ["algorithm", "plan", "flowchart", "sequence"],
    starter: "Why is planning useful before coding?",
    model: "Map one question, one answer, and one decision using a simple flowchart.",
    guided: "Plan a short quiz with at least two questions.",
    challenge: "Plan a score system or better user journey.",
    exitTicket: "A flowchart helps show the logic of a program before coding.",
    scratchHint: "Plan every question before opening Scratch.",
    teacherNote: "Insist on planning first. This lesson should reduce weaker code structure in the project phase.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "A flowchart helps you...", options: ["plan the logic", "draw better sprites", "record sound"], answer: 0 },
      { prompt: "An algorithm is...", options: ["a step-by-step set of instructions", "a game character", "a background"], answer: 0 },
    ],
  },
  {
    id: "st1w7",
    term: "Summer Term 1",
    week: 7,
    title: "Debugging",
    shortTitle: "Fixing Logic",
    focus: "Finding and fixing errors in selection code",
    outcome: "I can test a program and fix logic mistakes.",
    vocab: ["debug", "error", "test", "fix"],
    starter: "What should you do if your quiz gives the wrong message?",
    model: "Show a broken condition, test it, then fix it.",
    guided: "Use a checklist to test and improve a script.",
    challenge: "Find two different bugs and explain what went wrong.",
    exitTicket: "Debugging means finding and fixing mistakes in code.",
    scratchHint: "Test every path: correct answer, wrong answer, and unusual answer.",
    teacherNote: "Reward careful testing language, not just correct final answers.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "Debugging means...", options: ["adding a sprite", "finding and fixing mistakes", "making a background"], answer: 1 },
      { prompt: "What should you do first when something is wrong?", options: ["Test it carefully", "Delete everything", "Ignore it"], answer: 0 },
    ],
  },
  {
    id: "st2w1",
    term: "Summer Term 2",
    week: 1,
    title: "Build a Quiz",
    shortTitle: "First Working Question",
    focus: "Creating the first question in a quiz",
    outcome: "I can build a working quiz question using input and selection.",
    vocab: ["quiz", "input", "condition", "feedback"],
    starter: "What makes a quiz feel interactive?",
    model: "Build one full question from ask to outcome.",
    guided: "Create one question with correct and incorrect feedback.",
    challenge: "Add sound, score, or better wording.",
    exitTicket: "A working quiz question needs a question, an answer, and a decision.",
    scratchHint: "Start with one excellent question before expanding the project.",
    teacherNote: "Do not let pupils rush to multiple questions before one question works cleanly.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "Which parts are needed for a quiz question?", options: ["Question, answer, decision", "Only a sprite", "Only a backdrop"], answer: 0 },
      { prompt: "Feedback in a quiz helps the user...", options: ["understand the result", "change the computer", "close Scratch"], answer: 0 },
    ],
  },
  {
    id: "st2w2",
    term: "Summer Term 2",
    week: 2,
    title: "Expand the Quiz",
    shortTitle: "Multiple Questions",
    focus: "Adding more questions and structure",
    outcome: "I can extend my quiz to include multiple questions.",
    vocab: ["extend", "structure", "score", "sequence"],
    starter: "How can you make a quiz feel more complete?",
    model: "Show how to repeat the question-answer-feedback pattern.",
    guided: "Add at least one more question to the quiz.",
    challenge: "Add a score or a final message.",
    exitTicket: "A longer quiz repeats the same logic structure clearly.",
    scratchHint: "Copy only what is needed. Keep the code organised.",
    teacherNote: "Focus on structure and readability, not just adding more content.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "What helps when adding more questions?", options: ["Keeping a clear structure", "Changing everything each time", "Removing feedback"], answer: 0 },
      { prompt: "A score can help users...", options: ["see how well they did", "rename sprites", "move the stage"], answer: 0 },
    ],
  },
  {
    id: "st2w3",
    term: "Summer Term 2",
    week: 3,
    title: "Testing and Improving",
    shortTitle: "Refining Accuracy",
    focus: "Checking quiz logic and improving reliability",
    outcome: "I can test my project and improve weak areas.",
    vocab: ["test", "improve", "logic", "edge case"],
    starter: "What if someone types the answer differently?",
    model: "Test several answers and spot where the logic breaks.",
    guided: "Use a testing table to check each question.",
    challenge: "Improve the quiz so it handles tricky answers better.",
    exitTicket: "Testing helps make a project more reliable.",
    scratchHint: "Ask a partner to try to break your quiz.",
    teacherNote: "This lesson should feel like quality assurance rather than extra decoration.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "Why test more than once?", options: ["To check different situations", "To make the screen brighter", "To add more sprites"], answer: 0 },
      { prompt: "An edge case is...", options: ["a tricky or unusual situation", "the edge of the stage", "a drawing tool"], answer: 0 },
    ],
  },
  {
    id: "st2w4",
    term: "Summer Term 2",
    week: 4,
    title: "Enhancing the Program",
    shortTitle: "Better User Experience",
    focus: "Improving the design and feedback of the quiz",
    outcome: "I can improve my project to make it clearer and more enjoyable.",
    vocab: ["enhance", "design", "user experience", "feedback"],
    starter: "What makes an app easy and enjoyable to use?",
    model: "Add better feedback, cleaner screens, and a stronger ending.",
    guided: "Improve text, sounds, layout, and responses.",
    challenge: "Add polished features without breaking the logic.",
    exitTicket: "Good design helps users understand and enjoy a program.",
    scratchHint: "Make the instructions and final result screen very clear.",
    teacherNote: "Push clarity, simplicity, and audience awareness.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "User experience means...", options: ["how the app feels to use", "how long the code is", "how big the sprite is"], answer: 0 },
      { prompt: "A stronger ending in a quiz can...", options: ["make it feel complete", "remove the score", "hide the questions"], answer: 0 },
    ],
  },
  {
    id: "st2w5",
    term: "Summer Term 2",
    week: 5,
    title: "Consolidation",
    shortTitle: "Final Project Review",
    focus: "Finishing, reviewing, and evaluating the quiz",
    outcome: "I can complete my quiz and reflect on what I learned.",
    vocab: ["evaluate", "review", "complete", "reflect"],
    starter: "What are you most proud of in your project?",
    model: "Review a completed example and discuss what makes it successful.",
    guided: "Finish the project and use a checklist for review.",
    challenge: "Write a short evaluation with one strength and one next step.",
    exitTicket: "Evaluation helps us recognise strengths and improve next time.",
    scratchHint: "Use your checklist before saying your project is finished.",
    teacherNote: "Build in time for pupil reflection and self-evaluation.",
    scratchEditorUrl: editorUrl,
    scratchStarterUrl: studioUrl,
    scratchEmbedUrl: embedUrl,
    questions: [
      { prompt: "Evaluation means...", options: ["thinking about how well something worked", "starting again", "copying code"], answer: 0 },
      { prompt: "A useful reflection includes...", options: ["a strength and a next step", "only colours", "a new sprite name"], answer: 0 },
    ],
  },
];

export const teacherResources = [
  {
    title: "Delivery Model",
    summary: "Predict → Model → Copy → Modify → Explain",
    detail: "Keep the coding visible and narrate why decisions are being made.",
  },
  {
    title: "Assessment Focus",
    summary: "Check conceptual understanding of selection.",
    detail: "Look for accurate explanation, testing, and whether pupils can describe why code follows one path and not another.",
  },
  {
    title: "Scratch Integration",
    summary: "Each lesson now includes editor and starter links.",
    detail: "Replace the placeholder studio and embed links with your own school Scratch projects when ready.",
  },
];
